// ...existing code...
<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
        // ...existing code...
        <hr class="sidebar-divider">
        <!-- Removed Alumni Events Section -->
        <hr class="sidebar-divider">
        // ...existing code...
    </ul>
</aside>
// ...existing code...
